disabled_rules:
- trailing_whitespace
- empty_count
- empty_enum_arguments
- empty_parentheses_with_trailing_closure
- multiple_closures_with_trailing_closure

opt_in_rules:
- empty_count
- empty_string
 
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

line_length:
 warning: 200
 error: 250
 
function_body_length:
 warning: 300
 error: 500
 
function_parameter_count:
 warning: 3
 error: 4
 
type_body_length:
 warning: 300
 error: 500
 
file_length:
 warning: 150
 error: 200
 ignore_comment_only_lines: true
 
cyclomatic_complexity:
 warning: 15
 error: 25
 
type_name:
 min_length: 4 # only warning
 max_length: # warning and error
 warning: 40
 error: 50

reporter: "xcode"
